server {
    listen 80;
    server_name localhost;

    # Логи (очень важно для отладки!)
    access_log /var/log/nginx/portfolio.access.log;
    error_log /var/log/nginx/portfolio.error.log;

    location / {
        # Перенаправляем трафик на наш Node.js
        proxy_pass http://127.0.0.1:3000;
        
        # Передаём заголовки, чтобы Node.js знал реальный IP клиента и протокол
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

