apiVersion: v1
kind: Secret
metadata:
  name: portfolio-app-secret
  labels:
    app: portfolio-app
type: Opaque
data:
  # base64 от "super-secret-password"
  REDIS_PASSWORD: c3VwZXItc2VjcmV0LXBhc3N3b3Jk
  # base64 от "my-api-key-12345"
  API_KEY: bXktYXBpLWtleS0xMjM0NQ==
