apiVersion: v1
kind: Service
metadata:
  name: portfolio-redis
spec:
  selector:
    app: redis              # ← Service будет направлять трафик на Pod'ы с label app=redis
  ports:
  - port: 6379              # ← Порт, по которому другие Pod'ы будут обращаться
    targetPort: 6379        # ← Порт внутри Pod'а
  type: ClusterIP           # ← Доступен только внутри кластера (не наружу)
